// ============================================================
// DevMetricsDash — README Generator
// ============================================================
// Auto-generates a beautiful README.md with embedded SVG charts.
// ============================================================

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import type { MetricsData } from "./types.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..");

function main() {
  const data: MetricsData = JSON.parse(
    readFileSync(join(ROOT, "data", "metrics.json"), "utf-8")
  );

  const s = data.summary;
  const generatedDate = new Date(data.generated_at).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const readme = `<div align="center">

# ⚡ DevMetricsDash

### Developer Metrics Dashboard — Auto-Updated Every Day

\`\`\`
📊 Tracking ${s.total_repositories} repositories · ${s.total_contributors} contributors · ${data.config.lookback_days} day window
\`\`\`

---

</div>

## 📈 Overview

<div align="center">

![Stats Banner](./assets/stats-banner.svg)

</div>

## 🔥 Contribution Activity

<div align="center">

![Contribution Heatmap](./assets/contribution-heatmap.svg)

</div>

## 📊 Activity Trends

<div align="center">

![Activity Chart](./assets/activity-chart.svg)

</div>

## 🔀 Pull Request Analytics

<div align="center">

![PR Stats](./assets/pr-stats.svg)

</div>

## 👥 Top Contributors

<div align="center">

![Top Contributors](./assets/top-contributors.svg)

</div>

## 🗂️ Language Breakdown

<div align="center">

![Languages](./assets/language-breakdown.svg)

</div>

## 🎯 DORA Metrics

<div align="center">

![DORA Metrics](./assets/dora-metrics.svg)

</div>

---

<div align="center">

### 📊 [View Full Interactive Dashboard →](https://${data.config.owner}.github.io/DevMetricsDash/)

</div>

---

## 🔧 Quick Start

### 1. Fork this repository

### 2. Add your GitHub token
Go to **Settings → Secrets → Actions** and add \`GH_PAT\` with a personal access token (needs \`repo\` scope).

### 3. Configure
Edit \`config.yml\` to set your username and which repos to track:

\`\`\`yaml
owner: "your-github-username"
repositories:
  - repo-1
  - repo-2
\`\`\`

### 4. Run
The GitHub Action runs automatically every day at 6 AM UTC, or you can trigger it manually from the Actions tab.

---

<div align="center">

📊 Auto-generated by **DevMetricsDash** on ${generatedDate}

<sub>⭐ Star this repo if you find it useful!</sub>

</div>
`;

  writeFileSync(join(ROOT, "README.md"), readme);
  console.log("✅ README.md generated with embedded SVG charts");
}

main();

